project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    other-links: 
      - text: GitHub Repo
        href: https://github.com/acti-rapi-1-sav-4-2024/proyecto-curso-dotnet
    comments:
      hypothesis: true
  agu-pdf: default
    #keep-tex: true

lang: es

execute:
  freeze: true



